<?php

namespace AppBundle\Repository;

/**
 * CarritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarritoRepository extends \Doctrine\ORM\EntityRepository
{
}
