<?php

namespace AppBundle\Repository;

/**
 * CatalogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogoRepository extends \Doctrine\ORM\EntityRepository
{
}
